Sync CI logging + makefile with service (#329)

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -7,7 +7,7 @@ ODHPROJECT=opendatahub
 # Specify the repo and git ref/branch to use for cloning ods-ci repo for the automation that works when running against an ODH deployment
 ODS_CI_REPO=https://github.com/red-hat-data-services/ods-ci
 ODS_CI_GITREF=master
-OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/latest/openshift-client-linux.tar.gz
+OC_CLI_URL=https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.14.33/openshift-client-linux.tar.gz
 # Authentication info for the OCP test user account that can be used in the test automation
 # For all tests, the expectation is that this is used for normal end-user access to the cluster
 OPENSHIFT_TESTUSER_NAME=
@@ -27,6 +27,8 @@ LOCAL?=false
 TEARDOWN?=false
 PLATFORM?=linux/amd64
 
+SERVICE_IMAGE?=quay.io/trustyai/trustyai-service:latest
+OPERATOR_IMAGE?=quay.io/trustyai/trustyai-service-operator:latest
 
 all: test
 test: build run clean
@@ -38,19 +40,34 @@ run:
 	mkdir -p ${LOCAL_ARTIFACT_DIR}/screenshots
 	oc config view --flatten --minify > /tmp/tests-kubeconfig
 	${BUILD_TOOL} run -e SKIP_INSTALL=$(SKIP_INSTALL) -e PYTEST_MARKERS=$(PYTEST_MARKERS) -e SKIP_OPERATOR_INSTALL=$(SKIP_OPERATOR_INSTALL) \
-	    -e SKIP_KFDEF_INSTALL=$(SKIP_KFDEF_INSTALL) -e ODHPROJECT=$(ODHPROJECT) \
+	    -e SKIP_DSC_INSTALL=$(SKIP_DSC_INSTALL) -e ODHPROJECT=$(ODHPROJECT) \
 		-e OPENSHIFT_TESTUSER_NAME="$(OPENSHIFT_TESTUSER_NAME)" -e OPENSHIFT_TESTUSER_PASS="$(OPENSHIFT_TESTUSER_PASS)" -e OPENSHIFT_TESTUSER_LOGIN_PROVIDER=$(OPENSHIFT_TESTUSER_LOGIN_PROVIDER) -e ARTIFACT_DIR=$(ARTIFACT_DIR) \
-		-e LOCAL=$(LOCAL) -e TEARDOWN=$(TEARDOWN)\
+		-e LOCAL=$(LOCAL) -e TEARDOWN=$(TEARDOWN) \
+		-e SERVICE_IMAGE=$(SERVICE_IMAGE) -e OPERATOR_IMAGE=$(OPERATOR_IMAGE)  \
 		-it -v ${LOCAL_ARTIFACT_DIR}/:$(ARTIFACT_DIR):z -v /tmp/tests-kubeconfig:/tmp/kubeconfig:z $(IMAGE)
 
+
+.SILENT:
 clean:
-	oc delete -n $(ODHPROJECT) kfdef odh-core || true
+	echo "============== Cleaning ODH Installation =============="
+	oc delete -n $(ODHPROJECT) dsc default-dsc || true
+	oc delete -n $(ODHPROJECT) dsci default-dsci || true
 	oc delete project $(ODHPROJECT) || echo -e "\n\n==> If the project deletion failed, you can try to use this script to force it: https://raw.githubusercontent.com/jefferyb/useful-scripts/master/openshift/force-delete-openshift-project\n\n"
-	#Clean up openshift-operators namespace
-	oc get csv -n openshift-operators -o name | grep strimzi-cluster-operator | xargs oc delete -n openshift-operators || true
-	oc get csv -n openshift-operators -o name | grep opendatahub-operator | xargs oc delete -n openshift-operators || true
-	oc delete subscription -n openshift-operators -l peak.test.subscription=opendatahub-operator
+
+	# Remove operator subscriptions, csvs
+	for operator in opendatahub authorino maria serverless servicemesh; do \
+  		echo "\n============== Deleting $$operator Operator Subscription and CSV ==============" ;\
+		oc delete $$(oc get subscription -n openshift-operators -o name | grep $$operator) -n openshift-operators || true ;\
+		oc delete $$(oc get clusterserviceversion -n openshift-operators -o name | grep $$operator) -n openshift-operators || true ;\
+	done
+
+	echo "\n============== Performing Cleanup =============="
+	# Other Cleanup
 	oc get mutatingwebhookconfiguration -o name | grep katib | grep $(ODHPROJECT) | xargs oc delete || true
 	oc get validatingwebhookconfiguration -o name | grep katib | grep $(ODHPROJECT) | xargs oc delete || true
-	oc delete project $(ODHPROJECT)-model || true
 	oc delete identity htpasswd-provider:admin || true
+
+	echo "\n============== Deleting CI Projects =============="
+	# Delete test projects"
+	oc delete $$(oc get projects -o name | grep basictests-) || true
+	oc delete $$(oc get projects -o name | grep nightly-) || true
